[package]
name = "graphics"
version = "0.2.1"
loft = ">=0.8"

[library]
entry = "src/graphics.loft"
native = "loft_graphics_native"

[native]
crate = "loft-graphics-native"
runtime-libs = "libGL.so.1, libasound.so.2"
build-deps = "libgl-dev, libasound2-dev"
