// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Native OpenGL support for the graphics package.
//! Uses glutin for window/context and gl for OpenGL bindings.

#![allow(clippy::missing_safety_doc)]
// The `loft_gl_*` / `loft_audio_*` entry points are the C-ABI FFI
// surface the loft runtime (and `--native` codegen) calls by symbol.
// They take raw `*const u8` / `*const f32` pointers handed over by the
// runtime and deref them via `loft_ffi::text` / `*ptr.add(i)`.  Marking
// them `unsafe fn` would change the signature `#[loft_native]` + the
// generated callers expect; the raw-pointer contract is upheld by the
// runtime caller, same rationale as the `missing_safety_doc` allow above.
#![allow(clippy::not_unsafe_ptr_arg_deref)]

use loft_ffi_macros::loft_native;

use glutin::prelude::*;
use std::cell::{Cell, RefCell};
use std::time::Duration;
use winit::application::ApplicationHandler;
use winit::event::WindowEvent;
use winit::event_loop::ActiveEventLoop;
use winit::platform::pump_events::{EventLoopExtPumpEvents, PumpStatus};
use winit::window::WindowId;

// Re-export audio functions at the crate root so external crates
// (e.g. the Rust source generated by `loft --native`) can call them as
// `loft_graphics_native::loft_audio_play`.  Keep the in-crate aliases
// for the bytecode dispatch macro below.
pub use audio::{
    loft_audio_load, loft_audio_play, loft_audio_play_raw, loft_audio_set_volume, loft_audio_stop,
};
mod audio;
use audio::n_audio_play_raw;
// Plan-25 F4: the audio bridges live in the `audio` module; bring them into
// scope so `loft_register_bridges!` (which takes bare idents) can see them.
use audio::{
    loft_audio_load__loft_bridge, loft_audio_play__loft_bridge,
    loft_audio_set_volume__loft_bridge, loft_audio_stop__loft_bridge,
    n_audio_play_raw__loft_bridge,
};
mod shader;
mod text;
mod window;

// ── Thread-local GL state ───────────────────────────────────────────────

struct GlState {
    #[allow(dead_code)] // kept alive to prevent window destruction
    window: winit::window::Window,
    surface: glutin::surface::Surface<glutin::surface::WindowSurface>,
    context: glutin::context::PossiblyCurrentContext,
    event_loop: winit::event_loop::EventLoop<()>,
    should_close: bool,
    // GL viewport size chosen at creation (selected-monitor size for
    // fullscreen) — returned by the window-size getters so callers don't
    // race the async inner_size update after a monitor move.
    viewport_w: u32,
    viewport_h: u32,
}

thread_local! {
    static GL: RefCell<Option<GlState>> = const { RefCell::new(None) };
    /// Set to `true` only after `gl::load_with` succeeds inside
    /// `loft_gl_create_window`.  Every function that calls a `gl::*`
    /// entry-point must check this first — when GL function pointers are
    /// not loaded, calling through them is undefined behaviour (P130).
    static GL_READY: Cell<bool> = const { Cell::new(false) };
}

/// Early-return when GL function pointers have not been loaded.
/// Use `gl_guard!()` in void functions and `gl_guard!(expr)` to return a
/// default value.
macro_rules! gl_guard {
    () => {
        if !GL_READY.with(|c| c.get()) {
            return;
        }
    };
    ($default:expr) => {
        if !GL_READY.with(|c| c.get()) {
            return $default;
        }
    };
}

fn with_gl<R>(f: impl FnOnce(&GlState) -> R) -> Option<R> {
    GL.with(|cell| cell.borrow().as_ref().map(f))
}

fn with_gl_mut<R>(f: impl FnOnce(&mut GlState) -> R) -> Option<R> {
    GL.with(|cell| cell.borrow_mut().as_mut().map(f))
}

// ── Input state ────────────────────────────────────────────────────────

thread_local! {
    static KEYS: RefCell<[bool; 256]> = const { RefCell::new([false; 256]) };
    static MOUSE_X: std::cell::Cell<f64> = const { std::cell::Cell::new(0.0) };
    static MOUSE_Y: std::cell::Cell<f64> = const { std::cell::Cell::new(0.0) };
    static MOUSE_BTN: std::cell::Cell<u8> = const { std::cell::Cell::new(0) };
    /// Initiative 03 Phase 1: scroll-wheel accumulator.  `MouseWheel`
    /// events add to this cell; `loft_gl_mouse_wheel` reads-and-resets.
    /// Positive = scroll up.  Pixel deltas are converted to integer
    /// line counts via a 20-px-per-line heuristic — winit reports
    /// either `LineDelta` (mouse) or `PixelDelta` (trackpad).
    static WHEEL_ACCUM: std::cell::Cell<i64> = const { std::cell::Cell::new(0) };
    /// Pending resize from a WindowEvent::Resized, applied after pump_app_events.
    static PENDING_RESIZE: std::cell::Cell<Option<(u32, u32)>> = const { std::cell::Cell::new(None) };
}

// Map winit key codes to a simple 0-255 index.
fn key_index(key: &winit::keyboard::Key) -> Option<u8> {
    use winit::keyboard::NamedKey;
    match key {
        winit::keyboard::Key::Character(c) => {
            let ch = c.chars().next()?;
            if ch.is_ascii() {
                Some(ch.to_ascii_lowercase() as u8)
            } else {
                None
            }
        }
        winit::keyboard::Key::Named(n) => match n {
            NamedKey::Space => Some(b' '),
            NamedKey::Enter => Some(b'\r'),
            NamedKey::Escape => Some(27),
            NamedKey::Tab => Some(9),
            NamedKey::ArrowUp => Some(128),
            NamedKey::ArrowDown => Some(129),
            NamedKey::ArrowLeft => Some(130),
            NamedKey::ArrowRight => Some(131),
            NamedKey::Shift => Some(132),
            NamedKey::Control => Some(133),
            // Initiative 03 Phase 1: F-keys for editor hotkeys.
            // F5 / F9 / F11 land at 134 / 138 / 140; siblings are
            // reserved even though the current editor only binds
            // F5 / F9 / F11, so later additions don't shift indices.
            NamedKey::F1 => Some(135),
            NamedKey::F2 => Some(136),
            NamedKey::F3 => Some(137),
            NamedKey::F4 => Some(138),
            NamedKey::F5 => Some(139),
            NamedKey::F6 => Some(140),
            NamedKey::F7 => Some(141),
            NamedKey::F8 => Some(142),
            NamedKey::F9 => Some(143),
            NamedKey::F10 => Some(144),
            NamedKey::F11 => Some(145),
            NamedKey::F12 => Some(146),
            _ => None,
        },
        _ => None,
    }
}

struct JsonApp {
    should_close: bool,
}

impl ApplicationHandler for JsonApp {
    fn resumed(&mut self, _event_loop: &ActiveEventLoop) {}
    fn window_event(&mut self, _el: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        match event {
            WindowEvent::CloseRequested => self.should_close = true,
            WindowEvent::KeyboardInput { event, .. } => {
                if let Some(idx) = key_index(&event.logical_key) {
                    KEYS.with(|k| k.borrow_mut()[idx as usize] = event.state.is_pressed());
                }
            }
            WindowEvent::CursorMoved { position, .. } => {
                MOUSE_X.with(|c| c.set(position.x));
                MOUSE_Y.with(|c| c.set(position.y));
            }
            WindowEvent::MouseInput { state, button, .. } => {
                let bit = match button {
                    winit::event::MouseButton::Left => 1u8,
                    winit::event::MouseButton::Right => 2,
                    winit::event::MouseButton::Middle => 4,
                    _ => 0,
                };
                MOUSE_BTN.with(|c| {
                    if state.is_pressed() {
                        c.set(c.get() | bit);
                    } else {
                        c.set(c.get() & !bit);
                    }
                });
            }
            WindowEvent::MouseWheel { delta, .. } => {
                use winit::event::MouseScrollDelta;
                let ticks: i64 = match delta {
                    MouseScrollDelta::LineDelta(_dx, dy) => dy as i64,
                    // Trackpad pixel-delta: convert with a 20 px/line
                    // heuristic; matches the default scroll granularity
                    // most 3D apps use.
                    MouseScrollDelta::PixelDelta(p) => (p.y / 20.0) as i64,
                };
                if ticks != 0 {
                    WHEEL_ACCUM.with(|c| c.set(c.get() + ticks));
                }
            }
            WindowEvent::Resized(size) => {
                let w = size.width;
                let h = size.height;
                if w > 0 && h > 0 {
                    PENDING_RESIZE.with(|c| c.set(Some((w, h))));
                }
            }
            _ => {}
        }
    }
}

// ── C-ABI exports ───────────────────────────────────────────────────────

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_window(
    width: u32,
    height: u32,
    title_ptr: *const u8,
    title_len: usize,
) -> bool {
    let title = unsafe { loft_ffi::text(title_ptr, title_len) };
    match window::create_gl_state(width, height, title) {
        Ok(state) => {
            GL.with(|cell| *cell.borrow_mut() = Some(state));
            GL_READY.with(|c| c.set(true));
            true
        }
        Err(e) => {
            eprintln!("loft_gl_create_window: {e}");
            false
        }
    }
}

/// Initiative 03 Phase 0: borderless fullscreen companion to
/// `loft_gl_create_window`.  Opens on the primary monitor at its
/// native resolution.  Returns `true` on success.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_fullscreen_window(title_ptr: *const u8, title_len: usize) -> bool {
    let title = unsafe { loft_ffi::text(title_ptr, title_len) };
    match window::create_gl_state_fullscreen(title) {
        Ok(state) => {
            GL.with(|cell| *cell.borrow_mut() = Some(state));
            GL_READY.with(|c| c.set(true));
            true
        }
        Err(e) => {
            eprintln!("loft_gl_create_fullscreen_window: {e}");
            false
        }
    }
}

/// Initiative 03 Phase 4: toggle fullscreen on the existing window.
/// Cheaper than destroying + recreating the GL context — winit flips
/// the window mode at runtime and all GL resources (textures, VAOs,
/// shaders, FBOs) survive.  Pass `true` for borderless fullscreen on
/// the current monitor, `false` to return to the windowed size
/// `gl_create_window` originally opened.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_set_fullscreen(on: bool) {
    use winit::window::Fullscreen;
    with_gl(|s| {
        if on {
            s.window.set_fullscreen(Some(Fullscreen::Borderless(None)));
        } else {
            s.window.set_fullscreen(None);
        }
    });
}

/// Current window inner size in physical pixels.  Needed because a
/// fullscreen window opens at the monitor's native resolution, so callers
/// can't assume their windowed hint — query the real size to build the
/// projection / 2D ortho / overlay placement correctly.  Returns 0 if no
/// window exists.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_window_width() -> i64 {
    gl_guard!(0);
    with_gl(|s| s.viewport_w as i64).unwrap_or(0)
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_window_height() -> i64 {
    gl_guard!(0);
    with_gl(|s| s.viewport_h as i64).unwrap_or(0)
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_poll_events() -> bool {
    with_gl_mut(|s| {
        let mut handler = JsonApp {
            should_close: false,
        };
        let status = s
            .event_loop
            .pump_app_events(Some(Duration::ZERO), &mut handler);
        if handler.should_close || matches!(status, PumpStatus::Exit(_)) {
            s.should_close = true;
        }
        // Apply any pending resize — the handler can't borrow GlState directly.
        if let Some((w, h)) = PENDING_RESIZE.with(|c| c.take())
            && let (Some(nw), Some(nh)) =
                (std::num::NonZeroU32::new(w), std::num::NonZeroU32::new(h))
        {
            s.surface.resize(&s.context, nw, nh);
            unsafe {
                gl::Viewport(0, 0, w as i32, h as i32);
            }
            // Keep the window-size getters in sync with the actual
            // surface — otherwise `loft_gl_window_width/height` keep
            // returning the stale creation-time hint after the window
            // manager resizes the window to fit the screen, and any
            // screen-space UI hit-testing built on them is vertically
            // offset from where it draws.
            s.viewport_w = w;
            s.viewport_h = h;
        }
        !s.should_close
    })
    .unwrap_or(false)
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_swap_buffers() {
    gl_guard!();
    // On Wayland the compositor uses framebuffer alpha for window
    // transparency. Force the alpha channel to 1.0 (opaque) on every
    // frame before presenting, regardless of what shaders wrote.
    unsafe {
        gl::ColorMask(gl::FALSE, gl::FALSE, gl::FALSE, gl::TRUE);
        gl::ClearColor(0.0, 0.0, 0.0, 1.0);
        gl::Clear(gl::COLOR_BUFFER_BIT);
        gl::ColorMask(gl::TRUE, gl::TRUE, gl::TRUE, gl::TRUE);
    }
    with_gl(|s| {
        let _ = s.surface.swap_buffers(&s.context);
    });
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_clear(color: u32) {
    gl_guard!();
    // Color is packed as 0xAARRGGBB by graphics::rgba().
    let a = ((color >> 24) & 0xFF) as f32 / 255.0;
    let r = ((color >> 16) & 0xFF) as f32 / 255.0;
    let g = ((color >> 8) & 0xFF) as f32 / 255.0;
    let b = (color & 0xFF) as f32 / 255.0;
    unsafe {
        gl::ClearColor(r, g, b, a);
        gl::Clear(gl::COLOR_BUFFER_BIT | gl::DEPTH_BUFFER_BIT);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_destroy_window() {
    GL_READY.with(|c| c.set(false));
    GL.with(|cell| *cell.borrow_mut() = None);
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_shader(
    vert_ptr: *const u8,
    vert_len: usize,
    frag_ptr: *const u8,
    frag_len: usize,
) -> i64 {
    gl_guard!(0);
    let vert = unsafe { loft_ffi::text(vert_ptr, vert_len) };
    let frag = unsafe { loft_ffi::text(frag_ptr, frag_len) };
    i64::from(shader::compile_program(vert, frag).unwrap_or(0))
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_use_shader(program: i64) {
    gl_guard!();
    unsafe {
        gl::UseProgram(program as u32);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_upload_mesh(
    data_ptr: *const f32,
    n_vertices: u32,
    stride: u32,
    out_vao: *mut u32,
    out_vbo: *mut u32,
) {
    gl_guard!();
    let mut vao = 0u32;
    let mut vbo = 0u32;
    unsafe {
        gl::GenVertexArrays(1, &mut vao);
        gl::GenBuffers(1, &mut vbo);
        gl::BindVertexArray(vao);
        gl::BindBuffer(gl::ARRAY_BUFFER, vbo);
        let byte_size = (n_vertices * stride * 4) as isize;
        gl::BufferData(
            gl::ARRAY_BUFFER,
            byte_size,
            data_ptr.cast(),
            gl::STATIC_DRAW,
        );
        // Position: location 0, 3 floats
        gl::VertexAttribPointer(
            0,
            3,
            gl::FLOAT,
            gl::FALSE,
            (stride * 4) as i32,
            std::ptr::null(),
        );
        gl::EnableVertexAttribArray(0);
        // Normal: location 1, 3 floats at offset 12
        if stride >= 6 {
            gl::VertexAttribPointer(
                1,
                3,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (3 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(1);
        }
        // UV: location 2, 2 floats at offset 24 (when stride == 8: pos+normal+uv)
        if stride == 8 {
            gl::VertexAttribPointer(
                2,
                2,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (6 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(2);
        }
        // Color: location 2, 4 floats at offset 24 (when stride >= 10: pos+normal+color)
        if stride >= 10 {
            gl::VertexAttribPointer(
                2,
                4,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (6 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(2);
        }
        // Growth anchor + birth: location 3 = vec3 anchor at offset 40,
        // location 4 = float birth at offset 52 (when stride >= 14:
        // pos+normal+color+anchor+birth).  Used by the projector's
        // GPU crystal-growth shader to bloom each cell from its centre
        // by age — see tools/audience-demo/projector.loft CRYSTAL_VERT.
        if stride >= 14 {
            gl::VertexAttribPointer(
                3,
                3,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (10 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(3);
            gl::VertexAttribPointer(
                4,
                1,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (13 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(4);
        }
        gl::BindVertexArray(0);
        *out_vao = vao;
        *out_vbo = vbo;
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_draw(vao: i64, n_vertices: i64) {
    gl_guard!();
    unsafe {
        gl::BindVertexArray(vao as u32);
        gl::DrawArrays(gl::TRIANGLES, 0, n_vertices as i32);
        gl::BindVertexArray(0);
    }
}

// ── Store-aware GL functions (interpreter cdylib path — LoftStore/LoftRef) ───
//
// These are called at runtime by the interpreter via dynamic library loading.
// The interpreter's auto-marshalling passes LoftStore + LoftRef for vector args.
// Do NOT call these from native-compiled Rust code (loft_ffi version conflict).

/// Upload a vector<single> as a vertex buffer. Returns VAO handle.
/// stride = floats per vertex (3=pos, 6=pos+normal, 10=pos+normal+color).
/// Interpreter path: receives LoftStore + LoftRef for the data vector.
#[loft_native]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_gl_upload_vertices(
    store: loft_ffi::LoftStore,
    data: loft_ffi::LoftRef,
    stride: i64,
) -> i64 {
    gl_guard!(0);
    let count = unsafe { store.vector_len(&data) };
    let n_vertices = count / stride as u32;
    let data_ptr = unsafe { store.vector_data_ptr(&data) } as *const f32;
    let mut vao = 0u32;
    let mut vbo = 0u32;
    unsafe { loft_gl_upload_mesh(data_ptr, n_vertices, stride as u32, &mut vao, &mut vbo) };
    vao as i64
}

/// Set a mat4 uniform from a vector<float> (16 elements, column-major).
/// Interpreter path: receives LoftStore + LoftRef for the mat vector.
#[loft_native]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_gl_set_mat4(
    store: loft_ffi::LoftStore,
    program: i64,
    name_ptr: *const u8,
    name_len: usize,
    mat: loft_ffi::LoftRef,
) {
    gl_guard!();
    let name = unsafe { loft_ffi::text(name_ptr, name_len) };
    // Mat4.m is stored as vector<float> — 16 f64 values in the store.
    // OpenGL needs f32, so we convert on the fly.
    let count = unsafe { store.vector_len(&mat) };
    if count < 16 {
        return;
    }
    let mut buf = [0.0f32; 16];
    for (i, slot) in buf.iter_mut().enumerate() {
        let val = unsafe { store.get_float(mat.rec, 8 + i as u32 * 8, 0) };
        *slot = val as f32;
    }
    let c_name = std::ffi::CString::new(name).unwrap_or_default();
    unsafe {
        let loc = gl::GetUniformLocation(program as u32, c_name.as_ptr());
        if loc >= 0 {
            gl::UniformMatrix4fv(loc, 1, gl::FALSE, buf.as_ptr());
        }
    }
}

// ── Raw-pointer GL functions (native compilation path) ────────────────────
//
// These are called from loft-generated Rust code (--native).  The codegen
// extracts (*const ELEM_TYPE, count: u32) pairs from the stores directly,
// so no LoftStore or LoftRef is involved — no loft_ffi version conflict.

/// Upload a vertex buffer from a raw f32 pointer.  Returns VAO handle.
/// data_ptr/count: elements in the vector<single>; stride: floats per vertex.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_upload_vertices(
    data_ptr: *const f32,
    count: u32,
    stride: i64,
) -> i64 {
    gl_guard!(0);
    let n_vertices = if stride == 0 {
        0
    } else {
        count / stride as u32
    };
    let mut vao = 0u32;
    let mut vbo = 0u32;
    unsafe { loft_gl_upload_mesh(data_ptr, n_vertices, stride as u32, &mut vao, &mut vbo) };
    vao as i64
}

/// Set a mat4 uniform from a raw f64 pointer (vector<float> element type).
/// Converts the 16 f64 values to f32 before passing to OpenGL.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_set_mat4(
    program: i64,
    name_ptr: *const u8,
    name_len: usize,
    mat_ptr: *const f64,
    mat_count: u32,
) {
    gl_guard!();
    if mat_count < 16 {
        return;
    }
    let mut buf = [0.0f32; 16];
    for (i, slot) in buf.iter_mut().enumerate() {
        *slot = unsafe { *mat_ptr.add(i) } as f32;
    }
    let name = unsafe { loft_ffi::text(name_ptr, name_len) };
    let c_name = std::ffi::CString::new(name).unwrap_or_default();
    unsafe {
        let loc = gl::GetUniformLocation(program as u32, c_name.as_ptr());
        if loc >= 0 {
            gl::UniformMatrix4fv(loc, 1, gl::FALSE, buf.as_ptr());
        }
    }
}

// ── Uniform helpers ────────────────────────────────────────────────────

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_set_uniform_float(
    program: i64,
    name_ptr: *const u8,
    name_len: usize,
    val: f64,
) {
    gl_guard!();
    let name = unsafe { loft_ffi::text(name_ptr, name_len) };
    let c_name = std::ffi::CString::new(name).unwrap_or_default();
    unsafe {
        let loc = gl::GetUniformLocation(program as u32, c_name.as_ptr());
        if loc >= 0 {
            gl::Uniform1f(loc, val as f32);
        }
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_set_uniform_int(
    program: i64,
    name_ptr: *const u8,
    name_len: usize,
    val: i64,
) {
    gl_guard!();
    let name = unsafe { loft_ffi::text(name_ptr, name_len) };
    let c_name = std::ffi::CString::new(name).unwrap_or_default();
    unsafe {
        let loc = gl::GetUniformLocation(program as u32, c_name.as_ptr());
        if loc >= 0 {
            gl::Uniform1i(loc, val as i32);
        }
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_set_uniform_vec3(
    program: i64,
    name_ptr: *const u8,
    name_len: usize,
    x: f64,
    y: f64,
    z: f64,
) {
    gl_guard!();
    let name = unsafe { loft_ffi::text(name_ptr, name_len) };
    let c_name = std::ffi::CString::new(name).unwrap_or_default();
    unsafe {
        let loc = gl::GetUniformLocation(program as u32, c_name.as_ptr());
        if loc >= 0 {
            gl::Uniform3f(loc, x as f32, y as f32, z as f32);
        }
    }
}

// ── GL state management ───────────────────────────────────────────────

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_enable(cap: i64) {
    gl_guard!();
    let gl_cap = match cap {
        1 => gl::DEPTH_TEST,
        2 => gl::BLEND,
        3 => gl::CULL_FACE,
        _ => return,
    };
    unsafe {
        gl::Enable(gl_cap);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_disable(cap: i64) {
    gl_guard!();
    let gl_cap = match cap {
        1 => gl::DEPTH_TEST,
        2 => gl::BLEND,
        3 => gl::CULL_FACE,
        _ => return,
    };
    unsafe {
        gl::Disable(gl_cap);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_blend_func(src: i64, dst: i64) {
    gl_guard!();
    let map = |v: i64| -> u32 {
        match v {
            0 => gl::ZERO,
            1 => gl::ONE,
            2 => gl::SRC_ALPHA,
            3 => gl::ONE_MINUS_SRC_ALPHA,
            4 => gl::DST_ALPHA,
            5 => gl::ONE_MINUS_DST_ALPHA,
            _ => gl::ONE,
        }
    };
    unsafe {
        gl::BlendFunc(map(src), map(dst));
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_cull_face(face: i64) {
    gl_guard!();
    let f = if face == 0 { gl::BACK } else { gl::FRONT };
    unsafe {
        gl::CullFace(f);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_depth_mask(write: bool) {
    gl_guard!();
    unsafe {
        gl::DepthMask(if write { gl::TRUE } else { gl::FALSE });
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_viewport(x: i64, y: i64, w: i64, h: i64) {
    gl_guard!();
    unsafe {
        gl::Viewport(x as i32, y as i32, w as i32, h as i32);
    }
}

// ── Framebuffer objects ───────────────────────────────────────────────

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_framebuffer() -> i64 {
    gl_guard!(0);
    let mut fbo = 0u32;
    unsafe {
        gl::GenFramebuffers(1, &mut fbo);
    }
    fbo as i64
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_bind_framebuffer(fbo: i64) {
    gl_guard!();
    unsafe {
        gl::BindFramebuffer(gl::FRAMEBUFFER, fbo as u32);
    }
}

/// Attach a texture as the color (attachment=0) or depth (attachment=1) target.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_framebuffer_texture(fbo: i64, attachment: i64, tex: i64) {
    gl_guard!();
    let att = if attachment == 0 {
        gl::COLOR_ATTACHMENT0
    } else {
        gl::DEPTH_ATTACHMENT
    };
    unsafe {
        gl::BindFramebuffer(gl::FRAMEBUFFER, fbo as u32);
        gl::FramebufferTexture2D(gl::FRAMEBUFFER, att, gl::TEXTURE_2D, tex as u32, 0);
        if attachment == 1 {
            let mut color_type: i32 = 0;
            gl::GetFramebufferAttachmentParameteriv(
                gl::FRAMEBUFFER,
                gl::COLOR_ATTACHMENT0,
                gl::FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE,
                &mut color_type,
            );
            if color_type == gl::NONE as i32 {
                gl::DrawBuffer(gl::NONE);
                gl::ReadBuffer(gl::NONE);
            }
        }
        gl::BindFramebuffer(gl::FRAMEBUFFER, 0);
    }
}

/// Create a depth-only texture (for shadow mapping).
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_depth_texture(width: i64, height: i64) -> i64 {
    gl_guard!(0);
    let mut tex = 0u32;
    unsafe {
        gl::GenTextures(1, &mut tex);
        gl::BindTexture(gl::TEXTURE_2D, tex);
        gl::TexImage2D(
            gl::TEXTURE_2D,
            0,
            gl::DEPTH_COMPONENT as i32,
            width as i32,
            height as i32,
            0,
            gl::DEPTH_COMPONENT,
            gl::FLOAT,
            std::ptr::null(),
        );
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::NEAREST as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::NEAREST as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::CLAMP_TO_EDGE as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_T, gl::CLAMP_TO_EDGE as i32);
        gl::BindTexture(gl::TEXTURE_2D, 0);
    }
    tex as i64
}

/// Create an empty RGBA texture (for render-to-texture / post-processing).
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_create_color_texture(width: i64, height: i64) -> i64 {
    gl_guard!(0);
    let mut tex = 0u32;
    unsafe {
        gl::GenTextures(1, &mut tex);
        gl::BindTexture(gl::TEXTURE_2D, tex);
        gl::TexImage2D(
            gl::TEXTURE_2D,
            0,
            gl::RGBA as i32,
            width as i32,
            height as i32,
            0,
            gl::RGBA,
            gl::UNSIGNED_BYTE,
            std::ptr::null(),
        );
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::LINEAR as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::LINEAR as i32);
        gl::BindTexture(gl::TEXTURE_2D, 0);
    }
    tex as i64
}

/// Draw a fullscreen quad (for post-processing passes). Uses a built-in VAO.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_draw_fullscreen_quad() {
    gl_guard!();
    thread_local! {
        static QUAD_VAO: std::cell::Cell<u32> = const { std::cell::Cell::new(0) };
    }
    let vao = QUAD_VAO.with(|c| {
        let mut v = c.get();
        if v == 0 {
            let verts: [f32; 24] = [
                -1.0, -1.0, 0.0, 0.0, 1.0, -1.0, 1.0, 0.0, -1.0, 1.0, 0.0, 1.0, 1.0, -1.0, 1.0,
                0.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 0.0, 1.0,
            ];
            unsafe {
                let mut vbo = 0u32;
                gl::GenVertexArrays(1, &mut v);
                gl::GenBuffers(1, &mut vbo);
                gl::BindVertexArray(v);
                gl::BindBuffer(gl::ARRAY_BUFFER, vbo);
                gl::BufferData(gl::ARRAY_BUFFER, 96, verts.as_ptr().cast(), gl::STATIC_DRAW);
                gl::VertexAttribPointer(0, 2, gl::FLOAT, gl::FALSE, 16, std::ptr::null());
                gl::EnableVertexAttribArray(0);
                gl::VertexAttribPointer(1, 2, gl::FLOAT, gl::FALSE, 16, 8 as *const _);
                gl::EnableVertexAttribArray(1);
                gl::BindVertexArray(0);
            }
            c.set(v);
        }
        v
    });
    unsafe {
        gl::BindVertexArray(vao);
        gl::DrawArrays(gl::TRIANGLES, 0, 6);
        gl::BindVertexArray(0);
    }
}

// ── Input queries ─────────────────────────────────────────────────────

/// Returns true if the key (ASCII code or special code) is currently pressed.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_key_pressed(key_code: i64) -> bool {
    if !(0..=255).contains(&key_code) {
        return false;
    }
    KEYS.with(|k| k.borrow()[key_code as usize])
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_mouse_x() -> f64 {
    MOUSE_X.with(|c| c.get())
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_mouse_y() -> f64 {
    MOUSE_Y.with(|c| c.get())
}

/// Returns bitmask: 1=left, 2=right, 4=middle.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_mouse_button() -> i64 {
    MOUSE_BTN.with(|c| c.get() as i64)
}

/// Initiative 03 Phase 1: accumulated scroll-wheel ticks since the
/// last call (positive = scroll up).  Reset on read so each call
/// returns only the delta since the previous one — suitable for the
/// editor's per-frame `InputState.in_wheel` field.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_mouse_wheel() -> i64 {
    WHEEL_ACCUM.with(|c| {
        let v = c.get();
        c.set(0);
        v
    })
}

// ── Indexed drawing (EBO) ─────────────────────────────────────────────

/// Upload vertex data + index buffer. Returns VAO handle.
/// Indices are u32, n_indices = number of index values.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_upload_indexed_mesh(
    vert_ptr: *const f32,
    n_vertices: u32,
    stride: u32,
    idx_ptr: *const u32,
    n_indices: u32,
    out_vao: *mut u32,
) {
    gl_guard!();
    let mut vao = 0u32;
    let mut vbo = 0u32;
    let mut ebo = 0u32;
    unsafe {
        gl::GenVertexArrays(1, &mut vao);
        gl::GenBuffers(1, &mut vbo);
        gl::GenBuffers(1, &mut ebo);
        gl::BindVertexArray(vao);
        gl::BindBuffer(gl::ARRAY_BUFFER, vbo);
        gl::BufferData(
            gl::ARRAY_BUFFER,
            (n_vertices * stride * 4) as isize,
            vert_ptr.cast(),
            gl::STATIC_DRAW,
        );
        gl::BindBuffer(gl::ELEMENT_ARRAY_BUFFER, ebo);
        gl::BufferData(
            gl::ELEMENT_ARRAY_BUFFER,
            (n_indices * 4) as isize,
            idx_ptr.cast(),
            gl::STATIC_DRAW,
        );
        // Same attribute layout as loft_gl_upload_mesh
        gl::VertexAttribPointer(
            0,
            3,
            gl::FLOAT,
            gl::FALSE,
            (stride * 4) as i32,
            std::ptr::null(),
        );
        gl::EnableVertexAttribArray(0);
        if stride >= 6 {
            gl::VertexAttribPointer(
                1,
                3,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (3 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(1);
        }
        if stride == 8 {
            gl::VertexAttribPointer(
                2,
                2,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (6 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(2);
        }
        if stride >= 10 {
            gl::VertexAttribPointer(
                2,
                4,
                gl::FLOAT,
                gl::FALSE,
                (stride * 4) as i32,
                (6 * 4) as *const _,
            );
            gl::EnableVertexAttribArray(2);
        }
        gl::BindVertexArray(0);
        *out_vao = vao;
    }
}

/// Draw using index buffer (EBO). mode: 0=triangles, 1=lines, 2=points.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_draw_elements(vao: i64, n_indices: i64, mode: i64) {
    gl_guard!();
    let gl_mode = match mode {
        1 => gl::LINES,
        2 => gl::POINTS,
        _ => gl::TRIANGLES,
    };
    unsafe {
        gl::BindVertexArray(vao as u32);
        gl::DrawElements(gl_mode, n_indices as i32, gl::UNSIGNED_INT, std::ptr::null());
        gl::BindVertexArray(0);
    }
}

/// Draw with explicit mode: 0=triangles, 1=lines, 2=points.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_draw_mode(vao: i64, n_vertices: i64, mode: i64) {
    gl_guard!();
    let gl_mode = match mode {
        1 => gl::LINES,
        2 => gl::POINTS,
        _ => gl::TRIANGLES,
    };
    unsafe {
        gl::BindVertexArray(vao as u32);
        gl::DrawArrays(gl_mode, 0, n_vertices as i32);
        gl::BindVertexArray(0);
    }
}

// ── GPU resource cleanup ──────────────────────────────────────────────

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_delete_shader(program: i64) {
    gl_guard!();
    unsafe {
        gl::DeleteProgram(program as u32);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_delete_vao(vao: i64) {
    gl_guard!();
    let v = vao as u32;
    unsafe {
        gl::DeleteVertexArrays(1, &v);
    }
}

#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_delete_framebuffer(fbo: i64) {
    gl_guard!();
    let f = fbo as u32;
    unsafe {
        gl::DeleteFramebuffers(1, &f);
    }
}

// ── Texture from alpha bitmap (for text rendering) ────────────────────

/// Upload an alpha-only bitmap as a GL texture with swizzle to white+alpha.
/// Used for text rendering: the font rasterizer produces alpha bitmaps.
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_upload_alpha_texture(
    data_ptr: *const u8,
    width: i32,
    height: i32,
) -> i32 {
    gl_guard!(0);
    let mut tex = 0u32;
    unsafe {
        gl::GenTextures(1, &mut tex);
        gl::BindTexture(gl::TEXTURE_2D, tex);
        gl::TexImage2D(
            gl::TEXTURE_2D,
            0,
            gl::RED as i32,
            width,
            height,
            0,
            gl::RED,
            gl::UNSIGNED_BYTE,
            data_ptr.cast(),
        );
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::LINEAR as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::LINEAR as i32);
        // Swizzle: sample as (1,1,1,r) so alpha comes from the red channel
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_SWIZZLE_A, gl::RED as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_SWIZZLE_R, gl::ONE as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_SWIZZLE_G, gl::ONE as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_SWIZZLE_B, gl::ONE as i32);
        gl::BindTexture(gl::TEXTURE_2D, 0);
    }
    tex as i32
}

/// Rasterize text and upload directly as a GL texture. Returns (tex_id, width, height).
/// Combines loft_gl_rasterize_text + loft_gl_upload_alpha_texture.
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_text_texture(
    font_idx: i32,
    text_ptr: *const u8,
    text_len: usize,
    size: f32,
    out_width: *mut i32,
    out_height: *mut i32,
) -> i32 {
    gl_guard!(0);
    let s = unsafe { loft_ffi::text(text_ptr, text_len) };
    let (w, h, pixels) = text::rasterize_text(font_idx, s, size);
    unsafe {
        *out_width = w as i32;
        *out_height = h as i32;
    }
    loft_gl_upload_alpha_texture(pixels.as_ptr(), w as i32, h as i32)
}

/// Save pixel data as a PNG file.  Pixels are 0xAARRGGBB packed
/// integers stored in loft's `vector<integer>` (i64 stride post-2c);
/// only the low 32 bits of each element carry the colour.
#[unsafe(no_mangle)]
pub extern "C" fn loft_save_png(
    path_ptr: *const u8,
    path_len: usize,
    width: i64,
    height: i64,
    data_ptr: *const i64,
    data_count: u32,
) -> bool {
    let path = unsafe { loft_ffi::text(path_ptr, path_len) };
    let w = width as u32;
    let h = height as u32;
    if w == 0 || h == 0 || data_count < w * h {
        return false;
    }
    let pixels = unsafe { std::slice::from_raw_parts(data_ptr, (w * h) as usize) };
    // Check if any pixel has alpha < 255 to decide RGB vs RGBA output.
    let has_alpha = pixels
        .iter()
        .any(|&elem| (((elem as u32) >> 24) & 0xFF) != 0xFF);
    let file = match std::fs::File::create(path) {
        Ok(f) => f,
        Err(_) => return false,
    };
    let mut encoder = png::Encoder::new(std::io::BufWriter::new(file), w, h);
    encoder.set_depth(png::BitDepth::Eight);
    if has_alpha {
        encoder.set_color(png::ColorType::Rgba);
        let mut rgba = Vec::with_capacity((w * h * 4) as usize);
        for &elem in pixels {
            let px = elem as u32;
            rgba.push(((px >> 16) & 0xFF) as u8); // R
            rgba.push(((px >> 8) & 0xFF) as u8); // G
            rgba.push((px & 0xFF) as u8); // B
            rgba.push(((px >> 24) & 0xFF) as u8); // A
        }
        let mut writer = match encoder.write_header() {
            Ok(w) => w,
            Err(_) => return false,
        };
        writer.write_image_data(&rgba).is_ok()
    } else {
        encoder.set_color(png::ColorType::Rgb);
        let mut rgb = Vec::with_capacity((w * h * 3) as usize);
        for &elem in pixels {
            let px = elem as u32;
            rgb.push(((px >> 16) & 0xFF) as u8); // R
            rgb.push(((px >> 8) & 0xFF) as u8); // G
            rgb.push((px & 0xFF) as u8); // B
        }
        let mut writer = match encoder.write_header() {
            Ok(w) => w,
            Err(_) => return false,
        };
        writer.write_image_data(&rgb).is_ok()
    }
}

/// Capture the current GL back-buffer to an RGB PNG.  Reads `GL_BACK`
/// (call before `gl_swap_buffers`, after the frame's draws) and flips the
/// rows, since GL's origin is bottom-left while PNG is top-left.  Lets us
/// inspect the live 3D output even on a headless / Wayland desktop where
/// the window itself can't be grabbed by external tools.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_screenshot(
    width: i64,
    height: i64,
    path_ptr: *const u8,
    path_len: usize,
) -> bool {
    gl_guard!(false);
    if width <= 0 || height <= 0 {
        return false;
    }
    let path = unsafe { loft_ffi::text(path_ptr, path_len) };
    let w = width as usize;
    let h = height as usize;
    let mut buf = vec![0u8; w * h * 4];
    unsafe {
        gl::PixelStorei(gl::PACK_ALIGNMENT, 1);
        gl::ReadBuffer(gl::BACK);
        gl::ReadPixels(
            0,
            0,
            width as i32,
            height as i32,
            gl::RGBA,
            gl::UNSIGNED_BYTE,
            buf.as_mut_ptr() as *mut std::ffi::c_void,
        );
    }
    let file = match std::fs::File::create(path) {
        Ok(f) => f,
        Err(_) => return false,
    };
    let mut encoder = png::Encoder::new(std::io::BufWriter::new(file), w as u32, h as u32);
    encoder.set_depth(png::BitDepth::Eight);
    encoder.set_color(png::ColorType::Rgb);
    let mut writer = match encoder.write_header() {
        Ok(wr) => wr,
        Err(_) => return false,
    };
    let mut rgb = Vec::with_capacity(w * h * 3);
    for row in (0..h).rev() {
        let base = row * w * 4;
        for col in 0..w {
            let i = base + col * 4;
            rgb.push(buf[i]);
            rgb.push(buf[i + 1]);
            rgb.push(buf[i + 2]);
        }
    }
    writer.write_image_data(&rgb).is_ok()
}

/// Load an image file (PNG, JPG) and upload it as a GL texture. Returns texture ID (0 on failure).
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_load_texture(path_ptr: *const u8, path_len: usize) -> i64 {
    gl_guard!(0);
    let path = unsafe { loft_ffi::text(path_ptr, path_len) };
    let img = match image::open(path) {
        Ok(img) => img.to_rgba8(),
        Err(_) => return 0,
    };
    let (w, h) = img.dimensions();
    unsafe { loft_gl_upload_texture(img.as_raw().as_ptr(), w, h) as i64 }
}

/// Upload Canvas pixel data (0xAARRGGBB packed integers) as a GL RGBA
/// texture.  Post-2c, loft's `vector<integer>` is i64-stride storage —
/// each element occupies 8 bytes, with the packed colour in the LOW 32
/// bits and the high 32 bits zero.  Reading at the old i32 stride
/// (4-byte pixels) sees only every other "pixel" populated; the rest
/// were the high-half of the prior i64 = 0 = transparent black, which
/// shows up as moiré on textured surfaces and as missing pixels on
/// rasterised text (Brick Buster's title / HUD).  Read at i64 stride
/// to match the loft allocation; only the low 32 bits carry the
/// colour.
///
/// C58: canonical `(0, 0) = canvas top-left` — no upload-side Y flip.
/// GL's glTexImage2D stores the first buffer row as the texture's
/// bottom row, so canvas-top lives at TC.y=0 after upload.  The 2D
/// orthographic projection's `-2/H` already compensates for that when
/// mapping user-supplied top-left screen coords to GL clip-space, so
/// sprite and texture shaders can sample with identity V (no per-shader
/// flip).
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_upload_canvas(
    data_ptr: *const i64,
    data_count: u32,
    width: i64,
    height: i64,
) -> i64 {
    gl_guard!(0);
    let w = width as u32;
    let h = height as u32;
    if w == 0 || h == 0 || data_count < w * h {
        return 0;
    }
    let pixels = unsafe { std::slice::from_raw_parts(data_ptr, (w * h) as usize) };
    let mut rgba = Vec::with_capacity((w * h * 4) as usize);
    for &elem in pixels {
        let px = elem as u32; // low 32 bits hold the packed colour
        rgba.push(((px >> 16) & 0xFF) as u8); // R
        rgba.push(((px >> 8) & 0xFF) as u8); // G
        rgba.push((px & 0xFF) as u8); // B
        rgba.push(((px >> 24) & 0xFF) as u8); // A
    }
    unsafe { loft_gl_upload_texture(rgba.as_ptr(), w, h) as i64 }
}

// Interpreter wrapper — extracts vector data via LoftStore + LoftRef.
// Cannot use vec_wrapper! because the auto-marshaller's store snapshot
// may be stale for canvas data (issue #120 store lifecycle).
#[loft_native]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_gl_upload_canvas(
    store: loft_ffi::LoftStore,
    data: loft_ffi::LoftRef,
    width: i64,
    height: i64,
) -> i64 {
    gl_guard!(0);
    let count = unsafe { store.vector_len(&data) };
    let data_ptr = unsafe { store.vector_data_ptr(&data) } as *const i64;
    loft_gl_upload_canvas(data_ptr, count, width, height)
}
loft_ffi::vec_wrapper!(n_save_png, loft_save_png(path_ptr: *const u8, path_len: usize, width: i64, height: i64, data: vec<i64>) -> bool);
loft_ffi::vec_wrapper!(n_rasterize_text_into, loft_rasterize_text_into(font_idx: i64, text_ptr: *const u8, text_len: usize, size: f64, buf: vec<i64>) -> i64);

/// Return the line height in pixels for a font at the given size.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_text_height(_font_idx: i64, size: f64) -> i64 {
    (size as f32 * 1.2) as i64
}

/// @P340 — return the font's ASCENT in pixels (baseline → top of glyphs) from
/// fontdue's real horizontal line metrics.  Lets callers baseline-align
/// mixed-size text: the top-anchored `gl_draw_text(x, y)` places the baseline
/// at `y + gl_font_ascent(font, size)`, so two sizes sharing a baseline are
/// drawn at `y_i = baseline - gl_font_ascent(font, size_i)`.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_font_ascent(font_idx: i64, size: f64) -> f64 {
    f64::from(text::font_ascent(font_idx as i32, size as f32))
}

/// Rasterize text and write alpha values (0-255) into a pre-allocated
/// `vector<integer>` buffer.  Post-2c, `integer` storage is i64 stride
/// — write at i64 stride to match.  Pre-2c i32-stride writes left every
/// other slot's high half zero, which loft then read as a packed
/// alpha pair → only the low byte (alpha[2k]) survived the `& 255`
/// mask in `rgba`, so loft canvas pixel `k` showed `alpha[2k]` and
/// pixel `k+1` from row index `k+1` showed `alpha[2k+2]` — text
/// rasterised with every-other-pixel zero, the checker overlay
/// visible on Brick Buster's title.
#[unsafe(no_mangle)]
pub extern "C" fn loft_rasterize_text_into(
    font_idx: i64,
    text_ptr: *const u8,
    text_len: usize,
    size: f64,
    buf_ptr: *const i64,
    buf_count: u32,
) -> i64 {
    let s = unsafe { loft_ffi::text(text_ptr, text_len) };
    let (bw, bh, bitmap) = text::rasterize_text(font_idx as i32, s, size as f32);
    let count = (bw * bh) as usize;
    if count == 0 || buf_ptr.is_null() {
        return 0;
    }
    let buf = unsafe { std::slice::from_raw_parts_mut(buf_ptr as *mut i64, buf_count as usize) };
    for (i, &a) in bitmap.iter().enumerate() {
        if i >= buf.len() {
            break;
        }
        buf[i] = i64::from(a);
    }
    bw as i64
}

/// Set line width for GL_LINES rendering.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_line_width(width: f64) {
    gl_guard!();
    unsafe {
        gl::LineWidth(width as f32);
    }
}

/// Set point size for GL_POINTS rendering.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_point_size(size: f64) {
    gl_guard!();
    unsafe {
        gl::PointSize(size as f32);
    }
}

// ── Registration ────────────────────────────────────────────────────────

loft_ffi::loft_register! {
    loft_gl_create_window,
    loft_gl_create_fullscreen_window,
    loft_gl_set_fullscreen,
    loft_gl_window_width,
    loft_gl_window_height,
    loft_gl_mouse_wheel,
    loft_gl_poll_events,
    loft_gl_swap_buffers,
    loft_gl_clear,
    loft_gl_destroy_window,
    loft_gl_create_shader,
    loft_gl_use_shader,
    loft_gl_draw,
    loft_gl_bind_texture,
    loft_gl_delete_texture,
    loft_gl_load_font,
    loft_text_height,
    loft_gl_font_ascent,
    loft_rasterize_text_into => n_rasterize_text_into,
    loft_gl_measure_text,
    // Interpreter-aware versions (store + ref args instead of raw pointers)
    loft_gl_upload_vertices => n_gl_upload_vertices,
    loft_gl_set_mat4 => n_gl_set_mat4,
    // Uniform helpers
    loft_gl_set_uniform_float,
    loft_gl_set_uniform_int,
    loft_gl_set_uniform_vec3,
    // GL state
    loft_gl_enable,
    loft_gl_disable,
    loft_gl_blend_func,
    loft_gl_cull_face,
    loft_gl_depth_mask,
    loft_gl_viewport,
    // Framebuffer objects
    loft_gl_create_framebuffer,
    loft_gl_bind_framebuffer,
    loft_gl_framebuffer_texture,
    loft_gl_create_depth_texture,
    loft_gl_create_color_texture,
    loft_gl_draw_fullscreen_quad,
    // Input
    loft_gl_key_pressed,
    loft_gl_mouse_x,
    loft_gl_mouse_y,
    loft_gl_mouse_button,
    // Indexed drawing & draw modes
    loft_gl_draw_elements,
    loft_gl_draw_mode,
    // Cleanup
    loft_gl_delete_shader,
    loft_gl_delete_vao,
    loft_gl_delete_framebuffer,
    // Rendering hints
    loft_gl_line_width,
    loft_gl_point_size,
    // Texture loading
    loft_gl_load_texture,
    // Canvas → GL texture (interpreter-aware: store + ref for vector)
    loft_gl_upload_canvas => n_gl_upload_canvas,
    // PNG export
    loft_save_png => n_save_png,
    // GL framebuffer capture (headless-friendly screenshot)
    loft_gl_screenshot,
    // G5: Audio
    loft_audio_load,
    loft_audio_play,
    loft_audio_stop,
    loft_audio_set_volume,
    loft_audio_play_raw => n_audio_play_raw,
}

// Plan-25 F4: generated marshal bridges (the `#[loft_native]` siblings),
// registered under the same loft symbols.  Remap entries map the symbol to
// the interpreter-aware `n_*` rust fn's bridge.  The interpreter dispatches
// graphics through these; any symbol omitted here harmlessly falls back to
// the legacy raw-ptr arms (still present during the F4 transition).
loft_ffi::loft_register_bridges! {
    "loft_gl_create_window" => loft_gl_create_window__loft_bridge,
    "loft_gl_create_fullscreen_window" => loft_gl_create_fullscreen_window__loft_bridge,
    "loft_gl_set_fullscreen" => loft_gl_set_fullscreen__loft_bridge,
    "loft_gl_window_width" => loft_gl_window_width__loft_bridge,
    "loft_gl_window_height" => loft_gl_window_height__loft_bridge,
    "loft_gl_mouse_wheel" => loft_gl_mouse_wheel__loft_bridge,
    "loft_gl_poll_events" => loft_gl_poll_events__loft_bridge,
    "loft_gl_swap_buffers" => loft_gl_swap_buffers__loft_bridge,
    "loft_gl_clear" => loft_gl_clear__loft_bridge,
    "loft_gl_destroy_window" => loft_gl_destroy_window__loft_bridge,
    "loft_gl_create_shader" => loft_gl_create_shader__loft_bridge,
    "loft_gl_use_shader" => loft_gl_use_shader__loft_bridge,
    "loft_gl_draw" => loft_gl_draw__loft_bridge,
    "loft_gl_bind_texture" => loft_gl_bind_texture__loft_bridge,
    "loft_gl_delete_texture" => loft_gl_delete_texture__loft_bridge,
    "loft_gl_load_font" => loft_gl_load_font__loft_bridge,
    "loft_text_height" => loft_text_height__loft_bridge,
    "loft_gl_font_ascent" => loft_gl_font_ascent__loft_bridge,
    // loft_rasterize_text_into / loft_save_png use vec_wrapper! (no
    // #[loft_native] bridge) — they fall back to the legacy arms.
    "loft_gl_measure_text" => loft_gl_measure_text__loft_bridge,
    "loft_gl_upload_vertices" => n_gl_upload_vertices__loft_bridge,
    "loft_gl_set_mat4" => n_gl_set_mat4__loft_bridge,
    "loft_gl_set_uniform_float" => loft_gl_set_uniform_float__loft_bridge,
    "loft_gl_set_uniform_int" => loft_gl_set_uniform_int__loft_bridge,
    "loft_gl_set_uniform_vec3" => loft_gl_set_uniform_vec3__loft_bridge,
    "loft_gl_enable" => loft_gl_enable__loft_bridge,
    "loft_gl_disable" => loft_gl_disable__loft_bridge,
    "loft_gl_blend_func" => loft_gl_blend_func__loft_bridge,
    "loft_gl_cull_face" => loft_gl_cull_face__loft_bridge,
    "loft_gl_depth_mask" => loft_gl_depth_mask__loft_bridge,
    "loft_gl_viewport" => loft_gl_viewport__loft_bridge,
    "loft_gl_create_framebuffer" => loft_gl_create_framebuffer__loft_bridge,
    "loft_gl_bind_framebuffer" => loft_gl_bind_framebuffer__loft_bridge,
    "loft_gl_framebuffer_texture" => loft_gl_framebuffer_texture__loft_bridge,
    "loft_gl_create_depth_texture" => loft_gl_create_depth_texture__loft_bridge,
    "loft_gl_create_color_texture" => loft_gl_create_color_texture__loft_bridge,
    "loft_gl_draw_fullscreen_quad" => loft_gl_draw_fullscreen_quad__loft_bridge,
    "loft_gl_key_pressed" => loft_gl_key_pressed__loft_bridge,
    "loft_gl_mouse_x" => loft_gl_mouse_x__loft_bridge,
    "loft_gl_mouse_y" => loft_gl_mouse_y__loft_bridge,
    "loft_gl_mouse_button" => loft_gl_mouse_button__loft_bridge,
    "loft_gl_draw_elements" => loft_gl_draw_elements__loft_bridge,
    "loft_gl_draw_mode" => loft_gl_draw_mode__loft_bridge,
    "loft_gl_delete_shader" => loft_gl_delete_shader__loft_bridge,
    "loft_gl_delete_vao" => loft_gl_delete_vao__loft_bridge,
    "loft_gl_delete_framebuffer" => loft_gl_delete_framebuffer__loft_bridge,
    "loft_gl_line_width" => loft_gl_line_width__loft_bridge,
    "loft_gl_point_size" => loft_gl_point_size__loft_bridge,
    "loft_gl_load_texture" => loft_gl_load_texture__loft_bridge,
    "loft_gl_upload_canvas" => n_gl_upload_canvas__loft_bridge,
    "loft_gl_screenshot" => loft_gl_screenshot__loft_bridge,
    "loft_audio_load" => loft_audio_load__loft_bridge,
    "loft_audio_play" => loft_audio_play__loft_bridge,
    "loft_audio_stop" => loft_audio_stop__loft_bridge,
    "loft_audio_set_volume" => loft_audio_set_volume__loft_bridge,
    "loft_audio_play_raw" => n_audio_play_raw__loft_bridge,
}

// ── Text / Font C-ABI exports (GL3) ─────────────────────────────────────

/// Load a font from a file path. Returns font index (>= 0) on success, or
/// `i32::MIN` on error — that's loft's null sentinel for `integer`, so the
/// loft-side `if !font { … }` check works correctly. (Returning -1 would
/// look like a valid handle to loft, since -1 is not the null sentinel.
/// The bug that caused Brick Buster's score counter and every text texture in
/// 00-smoke.loft to be silently invisible was: -1 returned here, the loft
/// fallback path skipped, font_idx=-1 cast to usize=MAX in measure_text,
/// `fonts.get()` returns None, width returned as 0, canvas allocated as
/// 5×25, no glyphs fit.)
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_load_font(path_ptr: *const u8, path_len: usize) -> i64 {
    let path = unsafe { loft_ffi::text(path_ptr, path_len) };
    match std::fs::read(path) {
        // load_font_bytes returns a small font index, or -1 on parse failure.
        // Map -1 to loft's null sentinel (i64::MIN under the i64 ABI) so the
        // loft-side `if !font { … }` check fires — see the doc-comment above
        // for why a bare -1 would slip through as a valid-looking handle.
        Ok(data) => {
            let idx = text::load_font_bytes(&data);
            if idx < 0 { i64::MIN } else { i64::from(idx) }
        }
        Err(_) => i64::MIN,
    }
}

/// Measure text width in pixels at the given font size.
/// Takes and returns f64 to match loft's `float` type.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_measure_text(
    font_idx: i64,
    text_ptr: *const u8,
    text_len: usize,
    size: f64,
) -> f64 {
    let s = unsafe { loft_ffi::text(text_ptr, text_len) };
    text::measure_text(font_idx as i32, s, size as f32) as f64
}

/// Rasterize text into an alpha bitmap.
/// Caller must free the returned buffer with `loft_gl_free_bitmap`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_rasterize_text(
    font_idx: i32,
    text_ptr: *const u8,
    text_len: usize,
    size: f32,
    out_width: *mut u32,
    out_height: *mut u32,
    out_pixels: *mut *mut u8,
    out_pixels_len: *mut usize,
) {
    let s = unsafe { loft_ffi::text(text_ptr, text_len) };
    let (w, h, mut pixels) = text::rasterize_text(font_idx, s, size);
    unsafe {
        *out_width = w;
        *out_height = h;
        *out_pixels_len = pixels.len();
        *out_pixels = pixels.as_mut_ptr();
    }
    std::mem::forget(pixels);
}

/// Free a bitmap buffer allocated by `loft_gl_rasterize_text`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_free_bitmap(ptr: *mut u8, len: usize) {
    if !ptr.is_null() && len > 0 {
        drop(unsafe { Vec::from_raw_parts(ptr, len, len) });
    }
}

// ── Texture C-ABI exports (GL5.5) ──────────────────────────────────────

/// Upload an RGBA texture from a pixel buffer. Returns the texture ID.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn loft_gl_upload_texture(
    data_ptr: *const u8,
    width: u32,
    height: u32,
) -> u32 {
    gl_guard!(0);
    let mut tex = 0u32;
    unsafe {
        gl::GenTextures(1, &mut tex);
        gl::BindTexture(gl::TEXTURE_2D, tex);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MIN_FILTER, gl::LINEAR as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_MAG_FILTER, gl::LINEAR as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::CLAMP_TO_EDGE as i32);
        gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_T, gl::CLAMP_TO_EDGE as i32);
        gl::TexImage2D(
            gl::TEXTURE_2D,
            0,
            gl::RGBA as i32,
            width as i32,
            height as i32,
            0,
            gl::RGBA,
            gl::UNSIGNED_BYTE,
            data_ptr.cast(),
        );
        gl::BindTexture(gl::TEXTURE_2D, 0);
    }
    tex
}

/// Bind a texture to a texture unit for rendering.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_bind_texture(texture_id: i64, unit: i64) {
    gl_guard!();
    unsafe {
        gl::ActiveTexture(gl::TEXTURE0 + unit as u32);
        gl::BindTexture(gl::TEXTURE_2D, texture_id as u32);
    }
}

/// Delete a texture.
#[loft_native]
#[unsafe(no_mangle)]
pub extern "C" fn loft_gl_delete_texture(texture_id: i64) {
    gl_guard!();
    let texture_id = texture_id as u32;
    unsafe {
        gl::DeleteTextures(1, &texture_id);
    }
}
